## Variação da Taxa de Câmbio
```{r, echo=F, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}
library(readxl)
library(tidyverse)
library(ggplot2)
excinf <- read_excel("C:/Users/berrd/Desktop/China Data/Book11.xlsx", 
    sheet = "excinf")
excinf1 <- filter(excinf, Indicator > '1986')
View(excinf1)
ggplot(excinf1, aes(excinf1, x=Indicator, y=ExchangeRate, Group = 1))+
  geom_line(colour= 'red', size=1)+
  geom_hline(yintercept=0, colour='black', linetype='solid')+
  labs(x='Ano', y='Relação Renminbi para Dolár Americano',
       title='Relação RMB/USD',
       caption='Fonte: http://www.worldbank.org/') 
```

## Variação da Taxa de Câmbio e Inflação
```{r, echo=F, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}
library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)
excinf <- read_excel("C:/Users/berrd/Desktop/China Data/Book11.xlsx", 
    sheet = "excinf")
excinf1 <- filter(excinf, Indicator > '1986')
View(excinf1)
ggplot(excinf1, aes(x=Indicator))+
  geom_line(aes(y=percentage, colour='Variação da Taxa de Câmbio'), size=1)+
  geom_line(aes(y=Inflação, colour='Taxa de Inflação'), size=1)+
  geom_line(aes(y=juros, colour='Taxa de Juros Real'), size=1)+
  geom_hline(yintercept=0, colour='black', linetype='solid')+
  scale_colour_manual('', values=c('Variação da Taxa de Câmbio'='darkblue','Taxa de Inflação'='red', 'Taxa de Juros Real'='darkgreen'))+
  labs(x='', y='Variação Percentual',
       title='Variação da Taxa de Cãmbio, Inflação e Juros',
       caption='Fonte: http://www.worldbank.org/') 
```